services:
  ifood-lab:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USERNAME:-defaultuser}
    container_name: ifood-jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["start_notebook.sh"]
