services:
  ifood-lab:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ifood-lab
    ports:
      - "8888:8888"
    volumes:
      - .:/app:rw
    working_dir: /app  